name: Linux Build

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.7'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # Use PyInstaller to build ELF
      - name: Build ELF
        shell:
        run: |
          python3 -m pip install poetry
          python3 -m poetry install
          python3 -m poetry run pyinstaller kasatk.spec

      - name: Upload the PyInstaller Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: kasatk-linux-amd64
          path: ./dist/kasatk
          if-no-files-found: error

