name: Windows Build

on:
  push:
    #
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    # https://github.blog/changelog/2021-11-16-github-actions-windows-server-2022-with-visual-studio-2022-is-now-generally-available-on-github-hosted-runners/
    runs-on: windows-2022

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.7'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # Use PyInstaller to build EXE
      - name: Build Exe
        shell: pwsh
        run: |
          python.exe -m pip install poetry
          python.exe -m poetry install
          python.exe -m poetry run pyinstaller kasatk.spec

      # Save the created EXE file as a build artifact that may be downloaded
      - name: Upload the PyInstaller Windows Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: kasatk.exe
          path: ./dist/kasatk.exe
          if-no-files-found: error

